/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.awt.event.ActionListener;

/**
 *
 * @author Alif
 */
public class v_berandaAdmin extends javax.swing.JFrame {

    /**
     * Creates new form v_berandaAdmin
     */
    public v_berandaAdmin() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btn_pemesanan = new javax.swing.JButton();
        btn_user = new javax.swing.JButton();
        btn_keluar = new javax.swing.JButton();
        btn_logout = new javax.swing.JButton();
        btn_peramalan = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btn_pemesanan.setText("Pemesanan");
        getContentPane().add(btn_pemesanan, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 320, -1, -1));

        btn_user.setText("User");
        getContentPane().add(btn_user, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 320, -1, -1));

        btn_keluar.setText("Logout");
        getContentPane().add(btn_keluar, new org.netbeans.lib.awtextra.AbsoluteConstraints(1263, 822, -1, -1));

        btn_logout.setText("Logout");
        getContentPane().add(btn_logout, new org.netbeans.lib.awtextra.AbsoluteConstraints(1190, 20, -1, -1));

        btn_peramalan.setText("Peramalan");
        getContentPane().add(btn_peramalan, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 320, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/beranda_petani.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 4, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents
    public void addUserListener(ActionListener listener) {
        btn_user.addActionListener(listener);
    }

    public void addPemesananListener(ActionListener listener) {
        btn_pemesanan.addActionListener(listener);
    }
     public void addPeramalanListener(ActionListener listener) {
        btn_peramalan.addActionListener(listener);
    }
     public void addKeluarListener(ActionListener listener) {
        btn_keluar.addActionListener(listener);
    }
      public void addlogoutListener(ActionListener listener) {
        btn_logout.addActionListener(listener);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(v_berandaAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(v_berandaAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(v_berandaAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(v_berandaAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new v_berandaAdmin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_keluar;
    private javax.swing.JButton btn_logout;
    private javax.swing.JButton btn_pemesanan;
    private javax.swing.JButton btn_peramalan;
    private javax.swing.JButton btn_user;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
