/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.awt.event.ActionListener;
import javax.swing.JPasswordField;

/**
 *
 * @author Alif
 */
public class v_login extends javax.swing.JFrame {

    /**
     * Creates new form v_login
     */
    public v_login() {
        initComponents();
    }

    public String getTulis_password() {

        String pass = "";
        char passArray[] = tulis_password.getPassword();
        for (int i = 0; i < passArray.length; i++) {
            pass += passArray[i];
        }
        return pass;
    }

    public String getTulis_username() {
        return tulis_username.getText();
    }

    public void addLoginListener(ActionListener listener) {
        btn_login.addActionListener(listener);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tulis_username = new javax.swing.JTextField();
        btn_login = new javax.swing.JButton();
        tulis_password = new javax.swing.JPasswordField();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tulis_username.setBackground(new java.awt.Color(0, 0, 0));
        tulis_username.setCaretColor(new java.awt.Color(255, 255, 255));
        tulis_username.setOpaque(false);
        tulis_username.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tulis_usernameActionPerformed(evt);
            }
        });
        getContentPane().add(tulis_username, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 150, 150, 30));

        btn_login.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/btn_login.png"))); // NOI18N
        btn_login.setBorderPainted(false);
        btn_login.setContentAreaFilled(false);
        getContentPane().add(btn_login, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 310, 180, 70));

        tulis_password.setBackground(new java.awt.Color(0, 0, 0));
        tulis_password.setOpaque(false);
        tulis_password.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tulis_passwordActionPerformed(evt);
            }
        });
        getContentPane().add(tulis_password, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 210, 150, 30));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/bg_login.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 900, 540));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tulis_passwordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tulis_passwordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tulis_passwordActionPerformed

    private void tulis_usernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tulis_usernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tulis_usernameActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(v_login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(v_login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(v_login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(v_login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new v_login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_login;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPasswordField tulis_password;
    private javax.swing.JTextField tulis_username;
    // End of variables declaration//GEN-END:variables
}
