/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import com.toedter.calendar.JDateChooser;
import java.awt.event.ActionListener;
import java.awt.event.MouseListener;
import java.text.SimpleDateFormat;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JTable;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;
import java.text.SimpleDateFormat;
import java.util.Date;

/**
 *
 * @author Alif
 */
public class v_pemesanan extends javax.swing.JFrame {

    /**
     * Creates new form v_perusahaan
     */
    public v_pemesanan() {
        initComponents();

    }

    public JDateChooser getKalender() {
        return kalender;
    }


    public JLabel getTotal_stok() {
        return jLabel1;
    }

    public String getTulis_pesanan() {
        return tulis_pesanan.getText();
    }

    public void setTulis_pesanan(String pesan) {
        this.tulis_pesanan.setText(pesan);
    }

//    public JTextField getTulis_tanggal() {
//        return tulis_tanggal;
//    }
    public void cleardata() {
        tulis_pesanan.setText("");

    }

    
    public void addPesanListener(ActionListener listener) {
        btn_pesan.addActionListener(listener);
    }

    public void addKeluaristener(ActionListener listener) {
        btn_keluar.addActionListener(listener);
    }

    public void setTable1(DefaultTableModel tm) {
        jTable1.setModel(tm);
    }

    public void setTable(DefaultTableModel table) {
        this.jTable1.setModel(table);
    }

    public int getSelectedRow() {
        return jTable1.getSelectedRow();
    }

    public String getValueAt(int baris, int kolom) {
        return (String) this.jTable1.getValueAt(baris, kolom);
    }
     public void addTableListener(MouseListener listener) {
        jTable1.addMouseListener(listener);
    }
 

    public void addUpdateListener(ActionListener listener) {
        btn_update.addActionListener(listener);
    }

    public void addEditListener(ActionListener listener) {
        btn_edit.addActionListener(listener);
    }
    public void enableEdit() {
        btn_edit.setEnabled(true);
    }

    public void disableEdit() {
        btn_edit.setEnabled(false);
    }

    public void enableUpdate() {
        btn_update.setEnabled(true);
    }

    public void disableUpdate() {
        btn_update.setEnabled(false);
    }

    public void enablePesan() {
        btn_pesan.setEnabled(true);
    }

    public void disablePesan() {
        btn_pesan.setEnabled(false);
    }

   
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        tulis_pesanan = new javax.swing.JTextField();
        btn_pesan = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        btn_keluar = new javax.swing.JButton();
        btn_edit = new javax.swing.JButton();
        btn_update = new javax.swing.JButton();
        kalender = new com.toedter.calendar.JDateChooser();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 230, -1, -1));
        getContentPane().add(tulis_pesanan, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 160, 120, -1));

        btn_pesan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/btn_input.png"))); // NOI18N
        btn_pesan.setBorderPainted(false);
        btn_pesan.setContentAreaFilled(false);
        getContentPane().add(btn_pesan, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 280, -1, -1));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 110, -1, -1));

        btn_keluar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/btn_logout.png"))); // NOI18N
        btn_keluar.setContentAreaFilled(false);
        getContentPane().add(btn_keluar, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 0, -1, -1));

        btn_edit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/btn_edit.png"))); // NOI18N
        btn_edit.setContentAreaFilled(false);
        btn_edit.setEnabled(false);
        getContentPane().add(btn_edit, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 280, -1, -1));

        btn_update.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/btn_update.png"))); // NOI18N
        btn_update.setContentAreaFilled(false);
        btn_update.setEnabled(false);
        getContentPane().add(btn_update, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 320, -1, -1));
        getContentPane().add(kalender, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 210, -1, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/bg_pemesanan.png"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(v_pemesanan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(v_pemesanan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(v_pemesanan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(v_pemesanan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new v_pemesanan().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_edit;
    private javax.swing.JButton btn_keluar;
    private javax.swing.JButton btn_pesan;
    private javax.swing.JButton btn_update;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private com.toedter.calendar.JDateChooser kalender;
    private javax.swing.JTextField tulis_pesanan;
    // End of variables declaration//GEN-END:variables
}
