/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import com.toedter.calendar.JDateChooser;
import java.awt.event.ActionListener;
import javax.swing.JLabel;
import javax.swing.JTable;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Alif
 */
public class v_pemanenan extends javax.swing.JFrame {

   

    /**
     * Creates new form v_metodetanam
     */
    public v_pemanenan() {
        initComponents();
    }
 public int getLevel() {
        return combo.getSelectedIndex();
    }

    public void setLevel(int level) {
        this.combo.setSelectedIndex(level);
    }
    public void setInputStok(String input) {
        this.tulis_input.setText(input);
    }

//    public String getInputStok() {
//        return this.tulis_input.getText();
//    }

   

    public JTextField getTulis_input() {
        return tulis_input;
    }

    public JDateChooser getKalendar() {
        return kalendar;
    }

   
  public void setTable(DefaultTableModel tm) {
        jTable2.setModel(tm);
    }
    
    
 
  public void setuserLogin(String materi) {
        this.total_stok.setText(materi);
    }
    public void addInputStokListener(ActionListener listener) {
        btn_input.addActionListener(listener);
    }

    public void addKembaliListener(ActionListener listener) {
        btn_kembali.addActionListener(listener);
    }
     public void addPeriodeListener(ActionListener listener) {
        combo.addActionListener(listener);
    }
    public void cleardata() {
        tulis_input.setText("");
       
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        btn_kembali = new javax.swing.JButton();
        tulis_input = new javax.swing.JTextField();
        btn_input = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        total_stok = new javax.swing.JLabel();
        combo = new javax.swing.JComboBox<>();
        kalendar = new com.toedter.calendar.JDateChooser();
        jLabel1 = new javax.swing.JLabel();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btn_kembali.setText("kembali");
        getContentPane().add(btn_kembali, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 80, -1, -1));

        tulis_input.setForeground(new java.awt.Color(255, 255, 255));
        tulis_input.setOpaque(false);
        getContentPane().add(tulis_input, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 301, 220, 30));

        btn_input.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/Group 71.png"))); // NOI18N
        btn_input.setBorderPainted(false);
        btn_input.setContentAreaFilled(false);
        getContentPane().add(btn_input, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 440, -1, -1));

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTable2);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(582, 110, 520, 530));

        total_stok.setFont(new java.awt.Font("Bebas Neue", 2, 24)); // NOI18N
        total_stok.setForeground(new java.awt.Color(255, 255, 255));
        total_stok.setText("sotk");
        getContentPane().add(total_stok, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 80, 80, 60));

        combo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5" }));
        getContentPane().add(combo, new org.netbeans.lib.awtextra.AbsoluteConstraints(386, 140, 80, 30));
        getContentPane().add(kalendar, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 370, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/input_petani.png"))); // NOI18N
        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(v_pemanenan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(v_pemanenan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(v_pemanenan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(v_pemanenan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new v_pemanenan().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_input;
    private javax.swing.JButton btn_kembali;
    private javax.swing.JComboBox<String> combo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private com.toedter.calendar.JDateChooser kalendar;
    private javax.swing.JLabel total_stok;
    private javax.swing.JTextField tulis_input;
    // End of variables declaration//GEN-END:variables

    public JTable getjTable2() {
        return jTable2;
    }

    public JLabel getTotal_stok() {
        return total_stok;
    }

    
}
