/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.awt.event.ActionListener;
import java.awt.event.MouseListener;
import javax.swing.JComboBox;
import javax.swing.JTextArea;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Alif
 */
public class v_user extends javax.swing.JFrame {

    /**
     * Creates new form v_tambahUser
     */
    public v_user() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tulis_nama = new javax.swing.JTextField();
        combo = new javax.swing.JComboBox<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        tulis_alamat = new javax.swing.JTextArea();
        btn_tambah = new javax.swing.JButton();
        btn_edit = new javax.swing.JButton();
        btn_hapus = new javax.swing.JButton();
        tulis_password = new javax.swing.JTextField();
        btn_update = new javax.swing.JButton();
        tulis_username = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        btn_kembali = new javax.swing.JButton();
        id = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tulis_nama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tulis_namaActionPerformed(evt);
            }
        });
        getContentPane().add(tulis_nama, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 260, 150, 20));

        combo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Petani", "Perusahaan", "Admin" }));
        getContentPane().add(combo, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 370, 101, 34));

        tulis_alamat.setColumns(20);
        tulis_alamat.setRows(5);
        jScrollPane2.setViewportView(tulis_alamat);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 300, 170, 50));

        btn_tambah.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/btn_input.png"))); // NOI18N
        btn_tambah.setContentAreaFilled(false);
        getContentPane().add(btn_tambah, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 420, -1, -1));

        btn_edit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/btn_edit.png"))); // NOI18N
        btn_edit.setContentAreaFilled(false);
        btn_edit.setEnabled(false);
        getContentPane().add(btn_edit, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 420, -1, -1));

        btn_hapus.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/btn_hapus.png"))); // NOI18N
        btn_hapus.setContentAreaFilled(false);
        btn_hapus.setEnabled(false);
        getContentPane().add(btn_hapus, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 470, -1, -1));

        tulis_password.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tulis_passwordActionPerformed(evt);
            }
        });
        getContentPane().add(tulis_password, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 220, 150, 20));

        btn_update.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/btn_update.png"))); // NOI18N
        btn_update.setContentAreaFilled(false);
        btn_update.setEnabled(false);
        getContentPane().add(btn_update, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 470, -1, -1));
        getContentPane().add(tulis_username, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 180, 150, -1));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 100, 400, -1));

        btn_kembali.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/btn_kembali.png"))); // NOI18N
        btn_kembali.setContentAreaFilled(false);
        getContentPane().add(btn_kembali, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 0, -1, -1));

        id.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/bg_user.png"))); // NOI18N
        getContentPane().add(id, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tulis_passwordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tulis_passwordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tulis_passwordActionPerformed

    private void tulis_namaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tulis_namaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tulis_namaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(v_user.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(v_user.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(v_user.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(v_user.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new v_user().setVisible(true);
            }
        });

    }

    public int getLevel() {
        return combo.getSelectedIndex();
    }

    public void setLevel(int level) {
        this.combo.setSelectedIndex(level);
    }

    public String getTulis_alamat() {
        return tulis_alamat.getText();
    }

    public void setTulis_alamat(String alamat) {
        this.tulis_alamat.setText(alamat);
    }

    public String getTulis_Password() {
        return tulis_password.getText();
    }

    public void setTulis_password(String password) {
        this.tulis_password.setText(password);
    }

    public String getTulis_nama() {
        return tulis_nama.getText();
    }

    public void setTulis_nama(String tulis_nama) {
        this.tulis_nama.setText(tulis_nama);
    }

    public String getTulis_username() {
        return tulis_username.getText();
    }

    public String getID() {
        return id.getText();
    }

    public void setTulis_username(String tulis_username) {
        this.tulis_username.setText(tulis_username);
    }

    public void cleardata() {
        tulis_alamat.setText("");
        tulis_password.setText("");
        tulis_nama.setText("");
        tulis_username.setText("");

    }

    public void addTambahListener(ActionListener listener) {
        btn_tambah.addActionListener(listener);
    }

    public void addEditListener(ActionListener listener) {
        btn_edit.addActionListener(listener);
    }

    public void addHapusListener(ActionListener listener) {
        btn_hapus.addActionListener(listener);
    }

    public void addUpdateListener(ActionListener listener) {
        btn_update.addActionListener(listener);
    }

    public void setTable(DefaultTableModel table) {
        this.jTable1.setModel(table);
    }

    public int getSelectedRow() {
        return jTable1.getSelectedRow();
    }
 public void addKembaliListener(ActionListener listener) {
        btn_kembali.addActionListener(listener);
    }
    public String getValueAt(int baris, int kolom) {
        return (String) this.jTable1.getValueAt(baris, kolom);
    }

    public void enableEdit() {
        btn_edit.setEnabled(true);
    }

    public void disableEdit() {
        btn_edit.setEnabled(false);
    }

    public void enableDelete() {
        btn_hapus.setEnabled(true);
    }

    public void disableDelete() {
        btn_hapus.setEnabled(false);
    }

    public void enableUpdate() {
        btn_update.setEnabled(true);
    }

    public void disableUpdate() {
        btn_update.setEnabled(false);
    }

    public void disableTambah() {
        btn_tambah.setEnabled(false);
    }

    public void enableTambah() {
        btn_tambah.setEnabled(true);
    }

    public void addTableListener(MouseListener listener) {
        jTable1.addMouseListener(listener);
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_edit;
    private javax.swing.JButton btn_hapus;
    private javax.swing.JButton btn_kembali;
    private javax.swing.JButton btn_tambah;
    private javax.swing.JButton btn_update;
    private javax.swing.JComboBox<String> combo;
    private javax.swing.JLabel id;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextArea tulis_alamat;
    private javax.swing.JTextField tulis_nama;
    private javax.swing.JTextField tulis_password;
    private javax.swing.JTextField tulis_username;
    // End of variables declaration//GEN-END:variables
}
